#pragma once
#include <io.h>

using namespace std;
using namespace loader;

namespace Component {
	/*
		»ñÈ¡¹ÖÎïÃû³Æ
	*/
#pragma region GetMonsterName
	static string GetMonsterName(int id) {
		switch (id)
		{
		case 0:
			return u8"ĞUî€ıˆ";
		case 1:
			return u8"»ğıˆ";
		case 2:
			return u8"²İÊ³ıˆ";
		case 3:
			return u8"Ğ×²òıˆ";
		case 4:
			return u8"ÈÛÉ½ıˆ";
		case 5:
			return u8"¾úØi";
		case 6:
			return u8"Ò§ô~";
		case 7:
			return u8"´óĞ×²òıˆ";
		case 8:
			return u8"¹ÚÍ»ıˆ¡á";
		case 9:
			return u8"´Æ»ğıˆ";
		case 10:
			return u8"™Ñ»ğıˆ";
		case 11:
			return u8"Én»ğıˆ";
		case 12:
			return u8"½Çıˆ";
		case 13:
			return u8"ºÚ½Çıˆ";
		case 14:
			return u8"÷è÷ë";
		case 15:
			return u8"ØÏ£Ä¦Ë¹";
		case 16:
			return u8"ä“ıˆ";
		case 17:
			return u8"Ñ×åúıˆ";
		case 18:
			return u8"Ñ×Íõıˆ";
		case 19:
			return u8"ÈÛÑÒıˆ";
		case 20:
			return u8"¿Ö±©ıˆ";
		case 21:
			return u8"ÍÁÉ°ıˆ";
		case 22:
			return u8"±¬æmıˆ";
		case 23:
			return u8"Â¹Ê×¾«";
		case 24:
			return u8"¶¾ÑıøB";
		case 25:
			return u8"œç±Mıˆ";
		case 26:
			return u8"Ú¤Ÿôıˆ";
		case 27:
			return u8"É¦øB";
		case 28:
			return u8"Ñ£øB";
		case 29:
			return u8"Äàô~ıˆ";
		case 30:
			return u8"ïwÀ×ıˆ";
		case 31:
			return u8"¸¡¿Õıˆ";
		case 32:
			return u8"ïLÆ¯ıˆ";
		case 33:
			return u8"´óĞ×î€ıˆ";
		case 34:
			return u8"‘K×¦ıˆ";
		case 35:
			return u8"¹Çæmıˆ";
		case 36:
			return u8"ŒÆÌ×ıˆ";
		case 37:
			return u8"ÑÒÙ\ıˆ";
		case 38:
			return u8"½kİxıˆ";
		case 39:
			return u8"±¬÷[ıˆ";
		case 40:
			return u8"±³¼×ıˆ";
		case 41:
			return u8"¾«ì`Â¹";
		case 42:
			return u8"¾«ì`Â¹";
		case 43:
			return u8"¾Ş¼×Ïx";
		case 44:
			return u8"¾Ş·ä";
		case 45:
			return u8"ĞĞÒíıˆ";
		case 46:
			return u8"¹ÚÍ»ıˆ¡â";
		case 47:
			return u8"·¼Òíıˆ";
		case 48:
			return u8"Øˆòáıˆ";
		case 49:
			return u8"ËáÒíıˆ";
		case 50:
			return u8"Ğ×î€ıˆ";
		case 51:
			return u8"¹Å´úÂ¹Ê×¾«";
		case 52:
			return u8"Í»“ôıˆ";
		case 53:
			return u8"í‘Òíıˆ";
		case 54:
			return u8"É¢ŸáÆ÷¹Ù";
		case 55:
			return u8"¡Á¸±É¢ŸáÆ÷¹Ù";
		case 56:
			return u8"ÆæÃæ×å";
		case 57:
			return u8"£¿£¿£¿";
		case 58:
			return u8"´Æ»ğıˆ£¿£¿£¿";
		case 59:
			return u8"¹ÚÍ»ıˆ";
		case 60:
			return u8"üS½ğÆæÃæ×å";
		case 61:
			return u8"ŞZıˆ";
		case 62:
			return u8"Ñ¸ıˆ";
		case 63:
			return u8"±ùÑÀıˆ";
		case 64:
			return u8"»ÌÅ­¿Ö±©ıˆ";
		case 65:
			return u8"Ëéıˆ";
		case 66:
			return u8"”Øıˆ";
		case 67:
			return u8"Áò”Øıˆ";
		case 68:
			return u8"À×î€ıˆ";
		case 69:
			return u8"Ë®ÑıøB";
		case 70:
			return u8"šÊÀœç±Mıˆ";
		case 71:
			return u8"¯w¶¾ıˆ";
		case 72:
			return u8"¸¡Ãßıˆ";
		case 73:
			return u8"ËªÒíïLÆ¯ıˆ";
		case 74:
			return u8"ƒ´×¦ıˆ";
		case 75:
			return u8"ìFÕÎŒÆÌ×ıˆ";
		case 76:
			return u8"¼tÉ±¬÷[ıˆ";
		case 77:
			return u8"±ùô~ıˆ";
		case 78:
			return u8"ÃÍÅ£ıˆ";
		case 79:
			return u8"±ù…âıˆ";
		case 80:
			return u8"äé²¨ıˆ";
		case 81:
			return u8"ÌìµØ»ÍÌäıˆ";
		case 82:
			return u8"²¨²¨";
		case 83:
			return u8"Ñ©Â¹";
		case 84:
			return u8"±ù²òÀÇ";
		case 85:
			return u8"¶¬Òíıˆ";
		case 86:
			return u8"«FÀp×å";
		case 87:
			return u8"»ÍºÚıˆ";
		case 88:
			return u8"½ğ»ğıˆ";
		case 89:
			return u8"ãy»ğıˆ";
		case 90:
			return u8"ºÚÀÇøB";
		case 91:
			return u8"½ğª{×Ó";
		case 92:
			return u8"¼¤°º½ğª{×Ó";
		case 93:
			return u8"ºÚŞZıˆ";
		case 94:
			return u8"À×ÀÇıˆ";
		case 95:
			return u8"ªzÀÇıˆ";
		case 96:
			return u8"ÃÍ±¬Ëéıˆ";
		case 97:
			return u8"Ú¤³àıˆ";
		case 98:
			return u8"Unavailable";
		case 99:
			return u8"‘ğºÛºÚÀÇøB";
		case 100:
			return u8"ËªÈĞ±ùÑÀıˆ";
		case 101:
			return u8"ºÚıˆ";
		default:
			return u8"Î´Öª¹ÖÎï";
		}
	}
}


